export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  imageUrl: string;
  imageHint: string;
  type: 'pulseira' | 'brinco' | 'colar' | 'anel' | 'conjunto' | 'bolsa' | 'cinto' | 'sandalia';
  style: 'boho' | 'indígena' | 'boho-chic';
  colors: string[];
  isNewArrival?: boolean;
  isPromotion?: boolean;
  promotionDetails?: string;
}

export const products: Product[] = [  {
    id: '1',
    name: 'Anel Yara da Floresta',
    description: 'Anel elegante inspirado na lenda da Iara, com pedras naturais brasileiras e acabamento em prata. Simboliza a conexão com as águas sagradas.',
    price: 125.90,
    imageUrl: '/products/anel.jpg',
    imageHint: 'forest goddess silver ring with natural Brazilian stones',
    type: 'anel',
    style: 'indígena',
    colors: ['prata', 'turquesa', 'verde'],
    isNewArrival: true,
  },
  {
    id: '2',
    name: 'Bolsa Amazônia Tecida',
    description: 'Bolsa única tecida à mão com fibras naturais da Amazônia. Design sustentável que carrega a alma da floresta brasileira.',
    price: 189.50,
    imageUrl: '/products/bolsa.jpg',
    imageHint: 'handwoven Amazon fiber bag with natural patterns',
    type: 'bolsa',
    style: 'indígena',
    colors: ['bege', 'marrom', 'verde oliva'],
    isPromotion: true,
    promotionDetails: '15% OFF - Edição Sustentável!',
  },
  {
    id: '3',
    name: 'Brincos Uirapuru Dourado',
    description: 'Brincos pendentes inspirados no canto do Uirapuru, ave sagrada da Amazônia. Trazem sorte e felicidade para quem os usa.',
    price: 78.00,
    imageUrl: '/products/brinco.jpg',
    imageHint: 'golden Uirapuru bird inspired pendant earrings',
    type: 'brinco',
    style: 'boho',
    colors: ['dourado', 'bronze', 'âmbar'],
    isNewArrival: true,
  },
  {
    id: '4',
    name: 'Cinto Carajás Étnico',
    description: 'Cinto largo com padrões geométricos inspirados na arte rupestre da Serra dos Carajás. Peça única que conta nossa história ancestral.',
    price: 145.75,
    imageUrl: '/products/cinto.jpg',
    imageHint: 'ethnic geometric belt inspired by Carajás cave paintings',
    type: 'cinto',
    style: 'indígena',
    colors: ['marrom', 'terracota', 'preto'],
  },
  {
    id: '5',
    name: 'Colar Jaci Lua Cheia',
    description: 'Colar com pingente lunar em homenagem à Jaci, deusa da lua na mitologia tupi-guarani. Feito com cristais e prata brasileira.',
    price: 156.00,
    imageUrl: '/products/colar.jpg',
    imageHint: 'Jaci moon goddess necklace with Brazilian crystals',
    type: 'colar',
    style: 'boho-chic',
    colors: ['prata', 'cristal', 'azul noturno'],
  },
  {
    id: '6',
    name: 'Colar Curupira Protetor',
    description: 'Colar de proteção com amuletos naturais, inspirado no guardião da floresta Curupira. Feito com sementes amazônicas e cordão de algodão.',
    price: 89.90,
    imageUrl: '/products/colar2.jpg',
    imageHint: 'Curupira forest guardian protection necklace with Amazon seeds',
    type: 'colar',
    style: 'indígena',
    colors: ['marrom', 'verde', 'bege'],
    isPromotion: true,
    promotionDetails: 'Proteção Ancestral - 20% OFF!',
  },
  {
    id: '7',
    name: 'Colar Iemanjá das Águas',
    description: 'Colar dedicado à Iemanjá, rainha dos mares. Com contas azuis como o oceano e pingente em forma de estrela-do-mar em madrepérola.',
    price: 134.25,
    imageUrl: '/products/colar3.jpg',
    imageHint: 'Iemanjá ocean queen necklace with blue beads and mother of pearl',
    type: 'colar',
    style: 'boho-chic',
    colors: ['azul oceano', 'prata', 'madrepérola'],
  },
  {
    id: '8',
    name: 'Colar Vitória-Régia Sagrada',
    description: 'Colar longo inspirado na lenda da Vitória-Régia. Com pingente floral em madeira certificada e detalhes em ouro velho.',
    price: 198.00,
    imageUrl: '/products/colar4.jpg',
    imageHint: 'sacred Victoria Regia water lily necklace with wood pendant',
    type: 'colar',
    style: 'boho',
    colors: ['madeira natural', 'ouro velho', 'verde água'],
    isNewArrival: true,
  },
  {
    id: '9',
    name: 'Colar Tupã do Trovão',
    description: 'Colar masculino robusto inspirado em Tupã, deus do trovão. Com pingente de pedra vulcânica brasileira e cordão de couro.',
    price: 167.50,
    imageUrl: '/products/colar5.jpg',
    imageHint: 'Tupã thunder god necklace with volcanic stone and leather cord',
    type: 'colar',
    style: 'indígena',
    colors: ['preto vulcânico', 'couro marrom', 'prata'],
  },
  {
    id: '10',
    name: 'Conjunto de Anéis Saci',
    description: 'Trio de anéis inspirados nas travessuras do Saci-Pererê. Cada anel representa uma fase da lua e traz proteção contra energias negativas.',
    price: 210.00,
    imageUrl: '/products/conjunto_aneis.jpg',
    imageHint: 'Saci trickster spirit ring set with moon phases',
    type: 'conjunto',
    style: 'boho-chic',
    colors: ['prata oxidada', 'ônix', 'cristal fumê'],
    isPromotion: true,
    promotionDetails: 'Trio Mágico - Compre 3 por 2!',
  },
  {
    id: '11',
    name: 'Conjunto Colares Guarani',
    description: 'Trio de colares sobrepostos com padrões tradicionais Guarani. Feitos com contas de açaí, sementes e fibras naturais.',
    price: 156.75,
    imageUrl: '/products/conjunto_colares.jpg',
    imageHint: 'Guarani layered necklaces set with açaí beads and natural fibers',
    type: 'conjunto',
    style: 'indígena',
    colors: ['roxo açaí', 'bege natural', 'marrom'],
  },
  {
    id: '12',
    name: 'Conjunto Anhangá Colar e Brinco',
    description: 'Set completo inspirado no espírito protetor Anhangá. Colar choker e brincos matching com cristais brasileiros e acabamento em bronze.',
    price: 245.90,
    imageUrl: '/products/conjunto_colar_e_brinco.jpg',
    imageHint: 'Anhangá spirit jewelry set with Brazilian crystals and bronze',
    type: 'conjunto',
    style: 'boho',
    colors: ['bronze antigo', 'cristal citrino', 'ametista'],
    isNewArrival: true,
  },
  {
    id: '13',
    name: 'Conjunto Pulseiras Capoeira',
    description: 'Set de 4 pulseiras inspiradas na ginga da capoeira. Cada uma representa um elemento: terra, água, fogo e ar.',
    price: 118.00,
    imageUrl: '/products/conjunto_pulseiras.jpg',
    imageHint: 'Capoeira dance inspired bracelet set representing four elements',
    type: 'conjunto',
    style: 'boho-chic',
    colors: ['terracota', 'azul', 'vermelho', 'branco'],
  },
  {
    id: '14',
    name: 'Conjunto Pulseiras Açaí',
    description: 'Trio de pulseiras feitas com sementes de açaí polidas e fio encerado. Representa a força e energia da Amazônia.',
    price: 89.50,
    imageUrl: '/products/conjunto_pulseiras2.jpg',
    imageHint: 'açaí seed bracelet trio with waxed cord from Amazon',
    type: 'conjunto',
    style: 'indígena',
    colors: ['roxo escuro', 'preto', 'bege'],
    isPromotion: true,
    promotionDetails: 'Energia Amazônica - 25% OFF!',
  },
  {
    id: '15',
    name: 'Conjunto Pulseiras Caju',
    description: 'Pulseiras delicadas com sementes de caju e contas de madeira brasileira. Design minimalista que celebra nossa flora.',
    price: 67.25,
    imageUrl: '/products/conjunto_pulseiras3.jpg',
    imageHint: 'delicate cashew seed bracelets with Brazilian wood beads',
    type: 'conjunto',
    style: 'boho',
    colors: ['bege claro', 'madeira natural', 'dourado'],
  },
  {
    id: '16',
    name: 'Conjunto Pulseiras Carnaval',
    description: 'Set vibrante de pulseiras que capturam a alegria do Carnaval brasileiro. Com miçangas coloridas e pingentes folheados.',
    price: 134.00,
    imageUrl: '/products/conjunto_pulseiras4.jpg',
    imageHint: 'vibrant Brazilian Carnival bracelet set with colorful beads',
    type: 'conjunto',
    style: 'boho-chic',
    colors: ['verde bandeira', 'amarelo ouro', 'azul real'],
    isNewArrival: true,
  },
  {
    id: '17',
    name: 'Pulseira Mãe-da-Mata',
    description: 'Pulseira especial dedicada à Mãe-da-Mata, protetora da floresta. Feita com cipó e sementes coletadas sustentavelmente.',
    price: 78.90,
    imageUrl: '/products/pulseira.jpg',
    imageHint: 'forest mother bracelet with sustainable vine and seeds',
    type: 'pulseira',
    style: 'indígena',
    colors: ['marrom cipó', 'verde musgo', 'bege semente'],
  },
  {
    id: '18',
    name: 'Sandália Pajé Sagrada',
    description: 'Sandália exclusiva com símbolos xamânicos bordados à mão. Feita com couro vegetal e sola de borracha natural da Amazônia.',
    price: 245.75,
    imageUrl: '/products/sandalia.jpg',
    imageHint: 'sacred shaman sandals with hand-embroidered symbols and natural rubber',
    type: 'sandalia',
    style: 'indígena',
    colors: ['couro natural', 'bordado multicolor', 'sola borracha'],    isPromotion: true,
    promotionDetails: 'Coleção Brasileira - Frete Grátis!',
  }
];

export const uniqueTypes = Array.from(new Set(products.map(p => p.type)));
export const uniqueStyles = Array.from(new Set(products.map(p => p.style)));
export const uniqueColors = Array.from(new Set(products.flatMap(p => p.colors)));
