export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  imageUrl: string;
  imageHint: string;
  type: 'vestido' | 'blusa' | 'calca' | 'saia' | 'casaco' | 'acessorio' | 'conjunto' | 'bolsa';
  style: 'vintage' | 'retro' | 'boho-vintage' | 'anos-80' | 'anos-90';
  colors: string[];
  isNewArrival?: boolean;
  isPromotion?: boolean;
  promotionDetails?: string;
}

export const products: Product[] = [
  {
    id: '1',
    name: 'Vestido Vintage Bordeaux',
    description: 'Vestido midi vintage dos anos 80, com corte atemporal e detalhes únicos. Uma peça de caráter e personalidade.',
    price: 185.90,
    imageUrl: '/products/anel.jpg',
    imageHint: 'vintage bordeaux midi dress with unique details',
    type: 'vestido',
    style: 'anos-80',
    colors: ['bordeaux', 'vinho', 'dourado'],
    isNewArrival: true,
  },
  {
    id: '2',
    name: 'Bolsa Vintage Couro',
    description: 'Bolsa de couro legítimo vintage, com pátina única que conta uma história. Peça atemporal e sofisticada.',
    price: 289.50,
    imageUrl: '/products/bolsa.jpg',
    imageHint: 'vintage leather handbag with unique patina',
    type: 'bolsa',
    style: 'vintage',
    colors: ['marrom', 'caramelo', 'cognac'],
    isPromotion: true,
    promotionDetails: '20% OFF - Peça Única!',
  },
  {
    id: '3',
    name: 'Blusa Vintage Seda',
    description: 'Blusa de seda vintage com estampa exclusiva. Sofisticação e elegância em uma peça única e especial.',
    price: 158.00,
    imageUrl: '/products/brinco.jpg',
    imageHint: 'vintage silk blouse with exclusive print',
    type: 'blusa',
    style: 'retro',
    colors: ['nude', 'dourado', 'pérola'],
    isNewArrival: true,
  },
  {
    id: '4',
    name: 'Acessório Vintage Statement',
    description: 'Cinto vintage de couro com fivela statement. Peça perfeita para transformar qualquer look.',
    price: 98.50,
    imageUrl: '/products/cinto.jpg',
    imageHint: 'vintage leather belt with statement buckle',
    type: 'acessorio',
    style: 'vintage',
    colors: ['preto', 'dourado', 'prata'],
  },
  {
    id: '5',
    name: 'Colar Vintage Dourado',
    description: 'Colar vintage com detalhes em ouro velho. Uma peça que adiciona sofisticação a qualquer produção.',
    price: 125.00,
    imageUrl: '/products/colar.jpg',
    imageHint: 'vintage golden necklace with antique gold details',
    type: 'acessorio',
    style: 'retro',
    colors: ['dourado', 'ouro velho', 'bronze'],
    isPromotion: true,
    promotionDetails: 'Últimas peças!',
  },
  {
    id: '6',
    name: 'Colar Vintage Pérolas',
    description: 'Colar de pérolas vintage com fechamento especial. Elegância clássica que nunca sai de moda.',
    price: 198.00,
    imageUrl: '/products/colar2.jpg',
    imageHint: 'vintage pearl necklace with special clasp',
    type: 'acessorio',
    style: 'vintage',
    colors: ['pérola', 'dourado', 'marfim'],
  },
  {
    id: '7',
    name: 'Colar Vintage Turquesa',
    description: 'Colar vintage com pedras turquesa genuínas. Peça boho-vintage com energia e personalidade.',
    price: 165.50,
    imageUrl: '/products/colar3.jpg',
    imageHint: 'vintage turquoise stone necklace',
    type: 'acessorio',
    style: 'boho-vintage',
    colors: ['turquesa', 'prata', 'azul'],
    isNewArrival: true,
  },
  {
    id: '8',
    name: 'Colar Vintage Madeira',
    description: 'Colar vintage em madeira nobre com acabamento artesanal. Peça sustentável e única.',
    price: 89.90,
    imageUrl: '/products/colar4.jpg',
    imageHint: 'vintage wooden necklace with artisanal finish',
    type: 'acessorio',
    style: 'boho-vintage',
    colors: ['madeira', 'natural', 'marrom'],
  },
  {
    id: '9',
    name: 'Colar Vintage Cristal',
    description: 'Colar vintage com cristais autênticos. Peça que irradia luz e sofisticação.',
    price: 245.00,
    imageUrl: '/products/colar5.jpg',
    imageHint: 'vintage crystal necklace radiating sophistication',
    type: 'acessorio',
    style: 'retro',
    colors: ['cristal', 'prata', 'transparente'],
    isPromotion: true,
    promotionDetails: 'Edição Especial - 15% OFF',
  },
  {
    id: '10',
    name: 'Conjunto Vintage Anéis',
    description: 'Conjunto de anéis vintage empilháveis. Cada peça conta uma história diferente.',
    price: 156.00,
    imageUrl: '/products/conjunto_aneis.jpg',
    imageHint: 'vintage stackable rings set',
    type: 'conjunto',
    style: 'vintage',
    colors: ['dourado', 'prata', 'rose gold'],
  },
  {
    id: '11',
    name: 'Conjunto Vintage Completo',
    description: 'Conjunto colar e brincos vintage, perfeito para ocasiões especiais. Elegância garantida.',
    price: 298.50,
    imageUrl: '/products/conjunto_colar_e_brinco.jpg',
    imageHint: 'vintage necklace and earrings complete set',
    type: 'conjunto',
    style: 'retro',
    colors: ['dourado', 'pérola', 'cristal'],
    isNewArrival: true,
  },
  {
    id: '12',
    name: 'Conjunto Colares Vintage',
    description: 'Conjunto de colares vintage para sobreposição. Crie looks únicos e cheios de personalidade.',
    price: 189.90,
    imageUrl: '/products/conjunto_colares.jpg',
    imageHint: 'vintage layered necklaces set',
    type: 'conjunto',
    style: 'boho-vintage',
    colors: ['dourado', 'bronze', 'cobre'],
  },
  {
    id: '13',
    name: 'Conjunto Pulseiras Vintage I',
    description: 'Conjunto de pulseiras vintage empilháveis. Cada peça com sua própria personalidade.',
    price: 125.50,
    imageUrl: '/products/conjunto_pulseiras.jpg',
    imageHint: 'vintage stackable bracelets set',
    type: 'conjunto',
    style: 'vintage',
    colors: ['dourado', 'prata', 'cobre'],
  },
  {
    id: '14',
    name: 'Conjunto Pulseiras Vintage II',
    description: 'Segunda coleção de pulseiras vintage com texturas e materiais variados.',
    price: 142.00,
    imageUrl: '/products/conjunto_pulseiras2.jpg',
    imageHint: 'vintage bracelets collection with varied textures',
    type: 'conjunto',
    style: 'retro',
    colors: ['prata', 'negro', 'cristal'],
    isPromotion: true,
    promotionDetails: 'Combo especial!',
  },
  {
    id: '15',
    name: 'Conjunto Pulseiras Vintage III',
    description: 'Terceira coleção com pulseiras vintage de época. Peças raras e especiais.',
    price: 178.90,
    imageUrl: '/products/conjunto_pulseiras3.jpg',
    imageHint: 'rare vintage bracelets from different eras',
    type: 'conjunto',
    style: 'anos-90',
    colors: ['dourado', 'âmbar', 'bronze'],
  },
  {
    id: '16',
    name: 'Conjunto Pulseiras Vintage IV',
    description: 'Quarta coleção exclusiva de pulseiras vintage. Para quem busca autenticidade.',
    price: 195.50,
    imageUrl: '/products/conjunto_pulseiras4.jpg',
    imageHint: 'exclusive vintage bracelets collection for authenticity seekers',
    type: 'conjunto',
    style: 'vintage',
    colors: ['prata', 'turquesa', 'coral'],
    isNewArrival: true,
  },
  {
    id: '17',
    name: 'Pulseira Vintage Única',
    description: 'Pulseira vintage statement piece. Uma peça que fala por si só.',
    price: 89.00,
    imageUrl: '/products/pulseira.jpg',
    imageHint: 'vintage statement bracelet that speaks for itself',
    type: 'acessorio',
    style: 'retro',
    colors: ['dourado', 'vermelho', 'âmbar'],
  },
  {
    id: '18',
    name: 'Sandália Vintage Couro',
    description: 'Sandália vintage de couro artesanal. Conforto e estilo atemporal.',
    price: 225.90,
    imageUrl: '/products/sandalia.jpg',
    imageHint: 'vintage artisanal leather sandals with timeless style',
    type: 'acessorio',
    style: 'boho-vintage',
    colors: ['caramelo', 'natural', 'marrom'],
    isPromotion: true,
    promotionDetails: 'Últimas peças do verão!',
  },
];
